#!/usr/bin/env ruby
#^syntax detection
site 'http://community.opscode.com/api/v1'
cookbook 'runit', '~> 1.5.14'
cookbook 'postgresql', '~> 3.4.14'
cookbook 'python', '~> 1.4.6'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'git', '~>4.1.0'
cookbook 'supervisor', '~> 0.4.12'
cookbook 'nginx', '~> 2.7.4'
cookbook 'vim', '~> 1.1.2'
cookbook 'redisio', '~> 1.0.0'
